### ISSUE TITLE
Not Yeeting

### ISSUE THREAD

**Issue by belongkl-baesys** [ThinkInvis/RoR2-Yeet#1]
Clicking on an inventory item does not do anything.
Log output "[Info : Unity Log] "yeet" is not a recognized ConCommand or ConVar"

Below log generated by clicking the first and second inventory items.
![RoR1-0_Yeet](https://user-images.githubusercontent.com/23462520/90968087-5d606280-e4b6-11ea-97a6-b897197739d0.PNG)

**Comment by belongkl-baesys** [comment]
Further testing shows it is a conflict with one or more mods. Mod load order has no impact, even when loading third it still occurs.

**Comment by belongkl-baesys** [comment]
Conflict with BossItemDrop.
https://thunderstore.io/package/sheen/BossItemDrop/
https://github.com/TotallySheen/ROR2Mods/tree/master/BossItemDrop

**Comment by belongkl-baesys** [comment]
Conflict with Raincoat.
https://thunderstore.io/package/Jarlyk/Raincoat/
https://github.com/Jarlyk/JarlykMods

No conflict with the dependency MiniRpcLib.

**Comment by ThinkInvis** [comment]
So as it turns out, this was a problem with *my* code which just so happened to not cause any problems -- even when it should have -- if certain other mods weren't installed. Not sure what the criteria for that was, but this seems to be fixed by 121ab35d13f0564a7560a3cf6f1297a22d5e8fdc.
