### ISSUE TITLE
Mark dropped items as unrecyclable

### ISSUE THREAD

**Issue by Eldog02** [ThinkInvis/RoR2-Yeet#10]
### Is your feature request related to a problem? Please describe.
Items can be continuously dropped, recycled, and picked back up. This can be abused to infinitely recycle items until you get a specific one. It can also be unwanted behavior if you have a recycler with a gesture.

### Describe the solution you'd like
Items that are dropped are marked as already recycled or unrecyclable so they cannot be targeted by the recycler.

**Comment by ThinkInvis** [comment]
Fixed in 6efc39e9d1b86166e00d7ae161addf405ec2a453.
