### ISSUE TITLE
Config to disable yeeting in SP

### ISSUE THREAD

**Issue by breadguyyy** [ThinkInvis/RoR2-Yeet#12]
Would like to be able to disable throwing items in SP in part to prevent cheese, but also because I set the yoink CD to 9999 in order reduce cheese and promote primarily using yeet for cooperative item trading in MP and it would be unfortunate if I accidentally clicked an item in SP and lost it for 9999 seconds lol

**Comment by ThinkInvis** [comment]
Exposed mod enabled state as a convar instead (9c9b4b35846e4d3d8049e9eb0a2fec6ec292c086). Type `yeet_on 1` or `yeet_on 0` in console to enable/disable the mod, respectively.
