### ISSUE TITLE
Items disappear when yeeted

### ISSUE THREAD

**Issue by rauscheb** [ThinkInvis/RoR2-Yeet#7]
### Describe the Bug
Items disappear upon being dropped.

### To Reproduce
1. Obtain an item
2. Click on item to throw it
3. Wait for item to finish throwing
4. See the item disappear.

### Expected Behavior
The item should drop on the ground after being thrown so it can be picked-up again.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-Yeet/files/8201211/LogOutput.log)

**Comment by duck-mon** [comment]
Experiencing the same behavior with a fresh install

**Comment by Littleevo** [comment]
same here!

**Comment by RyMaxim** [comment]
Dropping equipment works fine for me. Non-equipment items just disappear when dropped, even if I'm staring at the ground in front of my feet.

**Comment by rauscheb** [comment]
> Dropping equipment works fine for me. Non-equipment items just disappear when dropped, even if I'm staring at the ground in front of my feet.

I just tested this on my end and can confirm that dropping equipment items works as-intended. Non-equipment items continue to disappear after being thrown, regardless of location/distance.

**Comment by ThinkInvis** [comment]
Fixed in e15a7eb9ce48ed604b0922b78a553a75970df157.
