### ISSUE TITLE
Config to prevent (Void/specific) items from dropping, 

### ISSUE THREAD

**Issue by itsspher** [ThinkInvis/RoR2-Yeet#8]
### Is your feature request related to a problem? Please describe.
As of current, you can only disallow Lunar, Equipment, or all non-Equipment items from dropping.
Since the acquisition of Void items is an active decision on par with Lunar items, they shouldn't be allowed to be dropped to preserve the consequences of picking up the Void item.

### Describe the solution you'd like
Add a config option to disallow specific items, or more options for what groups of items can be dropped, i.e. selections for Void, White, Green, and Red.

**Comment by ThinkInvis** [comment]
Void category added in ed5fbaaf8e711ad1586c8b9d1565da10d29567e2. Keeping this issue open as a reminder to add more granular options later.

**Comment by ThinkInvis** [comment]
Implemented in d0df0f0d47d203e0b256392dda82664f14589ecd, 50064048b6b9e2bb58ed428025dfa56a20b0dc69, defac71fea2f439e078f7a9f5ff6ae126b815ad2.
